# Generated by Django 4.1.7 on 2023-03-24 10:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DHT11",
            fields=[
                (
                    "record_id",
                    models.AutoField(
                        default=0,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(2147483647),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("time", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "temperature",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MaxValueValidator(100.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(100.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "DHT11",
                "verbose_name_plural": "DHT11s",
            },
        ),
        migrations.CreateModel(
            name="Light",
            fields=[
                (
                    "record_id",
                    models.AutoField(
                        default=0,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(2147483647),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("time", models.DateTimeField(default=datetime.datetime.now)),
                ("intensity", models.IntegerField()),
            ],
            options={
                "verbose_name": "Light",
                "verbose_name_plural": "Lights",
            },
        ),
        migrations.CreateModel(
            name="Sound",
            fields=[
                (
                    "record_id",
                    models.AutoField(
                        default=0,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(2147483647),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("time", models.DateTimeField(default=datetime.datetime.now)),
                ("intensity", models.IntegerField()),
            ],
            options={
                "verbose_name": "Sound",
                "verbose_name_plural": "Sounds",
            },
        ),
        migrations.CreateModel(
            name="WaterSensor",
            fields=[
                (
                    "record_id",
                    models.AutoField(
                        default=0,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(2147483647),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("time", models.DateTimeField(default=datetime.datetime.now)),
                ("water_level", models.IntegerField()),
            ],
            options={
                "verbose_name": "Water Sensor",
                "verbose_name_plural": "Water Sensors",
            },
        ),
    ]
